# Problems found: 3
# Run `ameba --only Lint/UselessAssign` for details
Lint/UselessAssign:
  Description: Disallows useless variable assignments
  ExcludeTypeDeclarations: false
  Excluded:
    - spec/unit/board_spec.cr
    - spec/unit/spatial_spec.cr
    - src/spatial.cr
  Enabled: true
  Severity: Warning

# Problems found: 3
# Run `ameba --only Documentation/DocumentationAdmonition` for details
Documentation/DocumentationAdmonition:
  Description: Reports documentation admonitions
  Timezone: UTC
  Excluded:
    - src/spatial.cr
    - src/board.cr
    - src/piece.cr
  Admonitions:
    - TODO
    - FIXME
    - BUG
  Enabled: true
  Severity: Warning

# Problems found: 2
# Run `ameba --only Metrics/CyclomaticComplexity` for details
Metrics/CyclomaticComplexity:
  Description: Disallows methods with a cyclomatic complexity higher than `MaxComplexity`
  MaxComplexity: 10
  Excluded:
    - src/spatial.cr
    - src/board.cr
  Enabled: true
  Severity: Warning
